### PR TITLE
Removes invalid commas

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Comment by jondegenhardt** [comment]
Thanks for the fix! Surprising it didn't cause a problem earlier. Did this cause an issue in one of CI pipelines? If so I'll need to tag a new version.

**Comment by burner** [comment]
yeah the dub json parser is somewhat forgiving 

thanks for merging

**Comment by jondegenhardt** [comment]
I tagged a new version (1.4.1). This will get picked up in dlang CI builds, so any PRs needing the fix will get it.

Thanks again for the PR.

**Comment by burner** [comment]
thanks again for merging

**Pull request merged**
